name: antimax
description: Messenger app with audio & video calls
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.10.1
  cupertino_icons: ^1.0.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  firebase_messaging: ^16.0.0
  package_info_plus: ^8.3.1
  path_provider: ^2.1.2
  install_plugin: ^2.1.0
  flutter_webrtc: ^1.1.0
  permission_handler: ^12.0.1
  audioplayers: ^6.5.0
  uuid: ^4.3.3
  logger: ^2.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/ringback.mp3
    - assets/audio/ringing.mp3